version: '3.4'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: Savr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - savr_network

  savr.api:
    image: ${DOCKER_REGISTRY-}savrapi
    build:
      context: .
      dockerfile: Savr.API/Dockerfile
    depends_on:
      - postgres
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=Savr;Username=postgres-d;Password=admin"
    
    networks:
      - savr_network
  migrator:
    build:
      context: .
      dockerfile: Savr.API/Dockerfile
    depends_on:
      - postgres
    environment:
      ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=Savr;Username=postgres-d;Password=admin"
    entrypoint: >
      sh -c "
        echo 'Waiting for Postgres...';
        until pg_isready -h postgres -p 5432; do sleep 1; done;
        echo 'Running migrations...';

        dotnet tool install --global dotnet-ef;
        export PATH=\"$PATH:/root/.dotnet/tools\";

        dotnet ef database update --project Savr.Persistence --startup-project Savr.API;
        dotnet ef database update --project Savr.Identity --startup-project Savr.API;"

networks:
  savr_network:

volumes:
  postgres_data:
